
platform :ios, '10.0'

target 'GeofenceSwiftPodsExample' do
  
  use_frameworks!

  pod 'CleverTap-iOS-SDK'
  pod 'CleverTapGeofence', :path => '../../../'

  target 'GeofenceSwiftPodsExampleTests' do
    inherit! :search_paths
    
  end

  target 'GeofenceSwiftPodsExampleUITests' do
    
  end

end
