
platform :ios, '10.0'

target 'GeofenceSwiftPodsExample' do
  
  use_frameworks!

  pod 'CleverTapGeofence', :path => '../../../'
  pod 'CleverTap-iOS-SDK', :git => 'https://github.com/CleverTap/clevertap-ios-sdk.git', :branch => 'feature/geofence/SDK-255'
  

  target 'GeofenceSwiftPodsExampleTests' do
    inherit! :search_paths
    
  end

  target 'GeofenceSwiftPodsExampleUITests' do
    
  end

end
