
platform :ios, '10.0'

target 'GeofenceSwiftPodsExample' do
  
  use_frameworks!

  pod 'CleverTap-iOS-SDK', :git => 'https://github.com/CleverTap/clevertap-ios-sdk.git'
  pod 'CleverTap-Geofence-SDK', :path => '../../../'

  target 'GeofenceSwiftPodsExampleTests' do
    inherit! :search_paths
    
  end

  target 'GeofenceSwiftPodsExampleUITests' do
    
  end

end
